=== An3aClo/Java-and-Distributed-Systems/MyXML/build/classes/myxml/details.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->

<!ELEMENT suplier (name,address,product)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (street,city,zip)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT product (type,price,quantity)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

<!ATTLIST product vinNumber CDATA #REQUIRED>

=== An3aClo/Java-and-Distributed-Systems/MyXML/build/classes/myxml/final.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE suplier SYSTEM "details.dtd">


<suplier >
    <name>Andrea</name>    
    <address>
        <street>Correli Ave</street>
        <city>Cape Town</city>
        <zip>8000</zip>
    </address>
    <product vinNumber ="1111">
        <type>Shoes</type>
        <price>R100</price>
        <quantity>7</quantity>
    </product>    
</suplier>
